[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
pre-build = ["apt-get update", "apt install -y liblzma-dev protobuf-compiler"]

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"
pre-build = [
    "apt-get update",
    "apt install -y protobuf-compiler pkg-config autoconf automake autopoint",
    """PKG_CONFIG_ALL_STATIC=1 && \
    mkdir -p /tmp/rust-libs && \
    cd /tmp/rust-libs && \
    git clone https://git.tukaani.org/xz.git && \
    cd xz && \
    git checkout v5.4.3 && \
    CC=x86_64-linux-musl ./autogen.sh --no-po4a --no-doxygen && \
    CC=x86_64-linux-musl-gcc ./configure --disable-shared --host x86_64-unknown-linux-musl --disable-doc --disable-scripts && \
    cd src/liblzma/ && \
    make && \
    make install && \
    cd ../../../ && \
    rm -rf xz""",
]


[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt install -y liblzma-dev:arm64 protobuf-compiler",
]

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt install -y protobuf-compiler pkg-config autoconf automake autopoint libtool m4",
    """PKG_CONFIG_ALL_STATIC=1 && \
    mkdir -p /tmp/rust-libs && \
    cd /tmp/rust-libs && \
    git clone https://git.tukaani.org/xz.git && \
    cd xz && \
    git checkout v5.4.3 && \
    CC=aarch64-linux-musl ./autogen.sh --no-po4a --no-doxygen && \
    CC=aarch64-linux-musl-gcc ./configure --disable-shared --host aarch64-unknown-linux-musl --disable-doc --disable-scripts && \
    cd src/liblzma/ && \
    make && \
    make install && \
    cd ../../../ && \
    rm -rf xz""",
]

[target.arm-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main"
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt install -y liblzma-dev:armhf protobuf-compiler",
]

[target.arm-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-musleabihf:main"
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt install -y protobuf-compiler pkg-config autoconf automake autopoint libtool m4",
    """PKG_CONFIG_ALL_STATIC=1 && \
    mkdir -p /tmp/rust-libs && \
    cd /tmp/rust-libs && \
    git clone https://git.tukaani.org/xz.git && \
    cd xz && \
    git checkout v5.4.3 && \
    CC=arm-linux-musleabihf ./autogen.sh --no-po4a --no-doxygen && \
    CC=arm-linux-musleabihf-gcc ./configure --disable-shared --host arm-unknown-linux-musleabihf --disable-doc --disable-scripts && \
    cd src/liblzma/ && \
    make && \
    make install && \
    cd ../../../ && \
    rm -rf xz""",
]

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt install -y liblzma-dev:armhf protobuf-compiler",
]

[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main"
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt install -y protobuf-compiler pkg-config autoconf automake autopoint libtool m4",
    """PKG_CONFIG_ALL_STATIC=1 && \
    mkdir -p /tmp/rust-libs && \
    cd /tmp/rust-libs && \
    git clone https://git.tukaani.org/xz.git && \
    cd xz && \
    git checkout v5.4.3 && \
    CC=arm-linux-musleabihf ./autogen.sh --no-po4a --no-doxygen && \
    CC=arm-linux-musleabihf-gcc ./configure --disable-shared --host armv7-unknown-linux-musleabihf --disable-doc --disable-scripts && \
    cd src/liblzma/ && \
    make && \
    make install && \
    cd ../../../ && \
    rm -rf xz""",
]
