name: release
on:
  push:
    branches: [mainline]
  pull_request:
  workflow_dispatch:
env:
  CARGO_INCREMENTAL: 0
permissions:
  contents: write

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

          # Darwin
          - os: macos-latest
            target: aarch64-apple-darwin

          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            triplet: x64-windows-static-md

    steps:
      - name: Checkout repository
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Setup cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          key: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            file \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            liblzma-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.0-dev \
            patchelf \
            protobuf-compiler \
            wget

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install pkg-config protobuf xz

      - name: Install cmake on Windows
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@983956e4a5edce90f0dfcc38c1543077e668402b # v3.30.0

      - name: Install protoc on Windows
        if: runner.os == 'Windows'
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: "27.2"

      - name: Install vcpkg on Windows
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
        with:
          vcpkgDirectory: C:/vcpkg
          vcpkgGitCommitId: 1de2026f28ead93ff1773e6e680387643e914ea1
          doNotUpdateVcpkg: true

      - name: Install liblzma on Windows
        if: runner.os == 'Windows'
        run: |
          ${{ env.RUNVCPKG_VCPKG_ROOT }}/vcpkg.exe install liblzma --triplet ${{ matrix.triplet }}

      - name: Install Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: 1.1.20

      - name: Install Bun dependencies
        run: |
          bun install --exact --frozen-lockfile

      - name: Tauri release
        uses: tauri-apps/tauri-action@41242bd545b6d1310ffc1685fb8bb87e97f0b748 # v0.5.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseDraft: true
          args: --target ${{ matrix.target }}
